events { worker_connections 1024; }

http {
    upstream frontend_nodes {
        server 10.0.2.5:8081; 
        server 10.0.2.4:8081; 
    }

    upstream backend_nodes {
        server 10.0.2.5:8000; 
        server 10.0.2.4:8000; 
    }

    upstream redmine_nodes {
        server 10.0.2.5:8085; 
        server 10.0.2.4:8085; 
    }

    # Редирект с HTTP на HTTPS
    server {
        listen 80;
        server_name mydevopsproject.club www.mydevopsproject.club redmine.mydevopsproject.club;
        return 301 https://$host$request_uri;
    }

    # СЕРВЕР ДИПЛОМНОЙ РАБОТЫ
    server {
        listen 443 ssl;
        server_name mydevopsproject.club www.mydevopsproject.club;

        ssl_certificate /etc/nginx/ssl/example.crt;
        ssl_certificate_key /etc/nginx/ssl/example.key;

        # Бэкенд (Django API)
        location /api/ {
            proxy_pass http://backend_nodes;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

        # Статические файлы (js, css, картинки)
        location ~* \.(js|css|png|jpg|jpeg|gif|ico|svg|woff|woff2|ttf|eot)$ {
            proxy_pass http://frontend_nodes;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        # SPA-роутинг React (Перенаправляем пути /login, /register на index.html)
        location / {
            proxy_pass http://frontend_nodes/index.html;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }

    # СЕРВЕР REDMINE
    server {
        listen 443 ssl;
        server_name redmine.mydevopsproject.club;

        ssl_certificate /etc/nginx/ssl/example.crt;
        ssl_certificate_key /etc/nginx/ssl/example.key;

        location / {
            proxy_pass http://redmine_nodes;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }
}
